# Script for populating the database. You can run it as:
#
#     mix run priv/repo/seeds.exs
#
# Inside the script, you can read and write to any of your
# repositories directly:
#
#     TartuBike.Repo.insert!(%TartuBike.SomeSchema{})
#
# We recommend using the bang functions (`insert!`, `update!`
# and so on) as they will fail if something goes wrong.

alias TartuBike.{Repo, BikeSharing.Dock, BikeSharing.Bike, BikeSharing.Route, Accounts.User, Accounts.Membershiptype}

# User Admin
[%{name: "Administrator", username: "Admin", password: "roooot", dateofbirth: "1990-12-30", email: "admin@tt.ee", creditcard: "1111111111111111", balance: 150.0}]
|> Enum.map(fn data -> User.changeset(%User{}, data) end)
|> Enum.each(fn changeset -> Repo.insert!(changeset) end)

# Membership types
[
%{duration: "year", amount: 30, description: "1-year membership costs €30"},
%{duration: "week", amount: 10, description: "1-week membership costs €10"},
%{duration: "day",  amount:  5, description: "1-day membership costs €5"},
%{duration: "hour", amount:  2, description: "1-hour membership costs €2"}]
|> Enum.map(fn data -> Membershiptype.changeset(%Membershiptype{}, data) end)
|> Enum.each(fn changeset -> Repo.insert!(changeset) end)

# STATIONS
[
%{name: "Kalda tee", capacity: 18, status: "available", latitude: 58.37388226, longitude: 26.7524598},
%{name: "Kaunase puiestee", capacity: 14,status: "available", latitude: 58.37171147, longitude: 26.76374724},
%{name: "Annelinna keskus", capacity: 12,status: "available", latitude: 58.36999198, longitude: 26.76756802},
%{name: "Mõisavahe", capacity: 14,status: "available", latitude: 58.37249777, longitude: 26.77965084},
%{name: "Annelinna kiir", capacity: 16,status: "available", latitude: 58.37276649, longitude: 26.77505483},
%{name: "Annelinna gümnaasium", capacity: 8,status: "available", latitude: 58.37539738, longitude: 26.76965496},
%{name: "Annelinn", capacity: 16,status: "available", latitude: 58.37644152, longitude: 26.76413785},
%{name: "Anne saun", capacity: 12,status: "available", latitude: 58.37791801, longitude: 26.75198051},
%{name: "Papli", capacity: 11,status: "available", latitude: 58.37851038, longitude: 26.74520977},
%{name: "Turusild", capacity: 16,status: "available", latitude: 58.3784417, longitude: 26.7409281},
%{name: "Põhja puiestee", capacity: 9,status: "available", latitude: 58.3832315, longitude: 26.75575641},
%{name: "Roosi", capacity: 15,status: "available", latitude: 58.3833137, longitude: 26.72780729},
%{name: "ERM", capacity: 8, status: "available",latitude: 58.3942328, longitude: 26.74382791},
%{name: "Vahi", capacity: 12,status: "available", latitude: 58.40164767, longitude: 26.72246858},
%{name: "Orava", capacity: 9,status: "available", latitude: 58.39154608, longitude: 26.73030051},
%{name: "Rüütli", capacity: 15, status: "available",latitude: 58.38256694, longitude: 26.72110729},
%{name: "K. E. von Baeri", capacity: 8, status: "available",latitude: 58.3823227, longitude: 26.71418179},
%{name: "Näituse", capacity: 9, status: "available",latitude: 58.37904428, longitude: 26.70866624},
%{name: "Tulbi", capacity: 9,status: "available", latitude: 58.37127562, longitude: 26.69395847},
%{name: "Kannikese", capacity: 11,status: "available", latitude: 58.37705174, longitude: 26.68358736},
%{name: "W. Ostwaldi", capacity: 20, status: "available",latitude: 58.36673126, longitude: 26.69388559},
%{name: "Raja", capacity: 9, status: "available",latitude: 58.36171249, longitude: 26.69065438},
%{name: "Ränilinn", capacity: 5,status: "available", latitude: 58.35339279, longitude: 26.68435779},
%{name: "Tamme puiestee", capacity: 10, status: "available",latitude: 58.3542627, longitude: 26.69671491},
%{name: "Viie tee rist", capacity: 9,status: "available", latitude: 58.35511411, longitude: 26.70926692},
%{name: "Postimaja", capacity: 5, status: "available",latitude: 58.34570498, longitude: 26.71456927},
%{name: "Sõbra", capacity: 10, status: "available",latitude: 58.36521565, longitude: 26.72124059},
%{name: "Tamme staadion", capacity: 12,status: "available", latitude: 58.36764824, longitude: 26.71200197},
%{name: "Raudteejaam", capacity: 21,status: "available", latitude: 58.37447257, longitude: 26.70740195},
%{name: "Vanemuise park", capacity: 21,status: "available", latitude: 58.3735547, longitude: 26.71552225},
%{name: "TÜ raamatukogu", capacity: 21,status: "available", latitude: 58.37696588, longitude: 26.72200795},
%{name: "Aleksandri", capacity: 6, status: "available", latitude: 58.37615576, longitude: 26.72882871},
%{name: "Aura veekeskus", capacity: 18,status: "available", latitude: 58.37527303, longitude: 26.73451605},
%{name: "Sõpruse sild", capacity: 10,status: "available", latitude: 58.36924551, longitude: 26.7400975},
%{name: "Pargi", capacity: 11,status: "available", latitude: 58.37085994, longitude: 26.72730339},
%{name: "Kuu", capacity: 9,status: "available", latitude: 58.36695355, longitude: 26.72951188},
%{name: "Karete", capacity: 10, status: "available",latitude: 58.35011961, longitude: 26.72318064},
%{name: "Torni", capacity: 16,status: "available", latitude: 58.38746806, longitude: 26.69550393},
%{name: "Tähtvere spordipark", capacity: 9,status: "available", latitude: 58.38919653, longitude: 26.7063229},
%{name: "Aparaaditehas", capacity: 11,status: "available", latitude: 58.37061269, longitude: 26.71522847},
%{name: "Ülejõe park", capacity: 16, status: "available",latitude: 58.38118319, longitude: 26.72742022},
%{name: "J. Hurda", capacity: 11,status: "available", latitude: 58.38370437, longitude: 26.70833082},
%{name: "Uueturu", capacity: 24,status: "available", latitude: 58.37802809, longitude: 26.72619479},
%{name: "Raatuse kool", capacity: 14,status: "available", latitude: 58.38363833, longitude: 26.737063},
%{name: "Soola", capacity: 11,status: "available", latitude: 58.37728463, longitude: 26.73047327},
%{name: "AHHAA", capacity: 6, status: "available",latitude: 58.37690838, longitude: 26.73315958},
%{name: "Lossi", capacity: 11,status: "available", latitude: 58.37949369, longitude: 26.71631433},
%{name: "Kaare", capacity: 11, status: "available",latitude: 58.36632068, longitude: 26.70351708},
%{name: "Raatuse", capacity: 20,status: "available", latitude: 58.38249651, longitude: 26.73233732},
%{name: "EMÜ spordihoone", capacity: 13,status: "available", latitude: 58.38971302, longitude: 26.6942269},
%{name: "Lõunakeskus", capacity: 10,status: "available", latitude: 58.35809453, longitude: 26.67940317},
%{name: "Rahu", capacity: 13,status: "available", latitude: 58.35754987, longitude: 26.7216176},
%{name: "Tamme gümnaasium", capacity: 16,status: "available", latitude: 58.36417506, longitude: 26.68954374},
%{name: "Veeriku", capacity: 16,status: "available", latitude: 58.37558393, longitude: 26.69673597},
%{name: "Pirogovi plats", capacity: 18,status: "available", latitude: 58.38009177, longitude: 26.72099653},
%{name: "Magistri", capacity: 16,status: "available", latitude: 58.38079076, longitude: 26.72442328},
%{name: "Vabadussild", capacity: 10, status: "available",latitude: 58.38585931, longitude: 26.72393301},
%{name: "Põllu", capacity: 14, status: "available",latitude: 58.39933419, longitude: 26.71261652},
%{name: "Tarmeko", capacity: 11, status: "available",latitude: 58.36440469, longitude: 26.73998064},
%{name: "Sepa turg", capacity: 11,status: "available", latitude: 58.34940236, longitude: 26.7407956},
%{name: "Ihaste", capacity: 11, status: "available",latitude: 58.34490494, longitude: 26.77949123},
%{name: "Kvissentali", capacity: 9, status: "available",latitude: 58.40662982, longitude: 26.69597478},
%{name: "Maarjamõisa", capacity: 16, status: "available",latitude: 58.36916921, longitude: 26.69827055},
%{name: "Kopli", capacity: 16, status: "available",latitude: 58.34910936, longitude: 26.7135211},
%{name: "Delta", capacity: 20,status: "available", latitude: 58.38453131, longitude: 26.72574889},
%{name: "Riiamäe", capacity: 16, status: "available",latitude: 58.37412665, longitude: 26.72246426},
%{name: "Tamme kool", capacity: 16,status: "available", latitude: 58.36376641, longitude: 26.70673674},
%{name: "Eeden", capacity: 12, status: "available",latitude: 58.37337251, longitude: 26.751664},
%{name: "Kivilinna", capacity: 12, status: "available",latitude: 58.37933949, longitude: 26.76508777},
%{name: "Pallase", capacity: 20, status: "available",latitude: 58.35834836, longitude: 26.78693316},
%{name: "Märja", capacity: 20,status: "available", latitude: 58.36348289, longitude: 26.64898751},
%{name: "Paju", capacity: 16, status: "available",latitude: 58.38204973, longitude: 26.74756544},
%{name: "Ilmatsalu", capacity: 16,status: "available", latitude: 58.38762612, longitude: 26.56197516},
%{name: "Magaziini", capacity: 16,status: "available", latitude: 58.34308434, longitude: 26.72978919},
%{name: "Tervise", capacity: 20,status: "available", latitude: 58.3627675, longitude: 26.67998699},
%{name: "Tartu Maja", capacity: 20, status: "available",latitude: 58.38171845, longitude: 26.68515921},
%{name: "Jakobsoni", capacity: 20,status: "available", latitude: 58.38163085, longitude: 26.70205007},
%{name: "Ringtee", capacity: 20,status: "available", latitude: 58.34230771, longitude: 26.71572221},
%{name: "E-Kaubamaja", capacity: 20,status: "available", latitude: 58.36040567, longitude: 26.73096556},
%{name: "Hipodroomi", capacity: 0,status: "available", latitude: 58.35302773, longitude: 26.76661432},
%{name: "Rahinge", capacity: 0,status: "available", latitude: 58.3813603, longitude: 26.62038767},
%{name: "Ujula", capacity: 0,status: "available", latitude: 58.39230063, longitude: 26.71419512},
%{name: "Kaupmehe", capacity: 18,status: "available", latitude: 58.40300848, longitude: 26.74123168},
%{name: "Kõrveküla", capacity: 20, status: "available",latitude: 58.4201403, longitude: 26.76271567},
%{name: "Ihaste Coop", capacity: 17,status: "available", latitude: 58.35050531, longitude: 26.78845888},
%{name: "Luunja", capacity: 20, status: "available",latitude: 58.35545164, longitude: 26.87951386},
%{name: "Lähte", capacity: 20,status: "available", latitude: 58.49371459, longitude: 26.68343901},
%{name: "Kaubabaas", capacity: 0,status: "available", latitude: 58.38584822, longitude: 26.680565},
%{name: "Linnupargi", capacity: 20,status: "available", latitude: 58.36669245, longitude: 26.76118155},
%{name: "Virtuaalne", capacity: 0,status: "available", latitude: 58.38904303, longitude: 26.7309308},
]
|> Enum.map(fn data -> Dock.changeset(%Dock{}, data) end)
|> Enum.each(fn changeset -> Repo.insert!(changeset) end)

# BIKES
# Statue = available | in-use | booked | off-duty
# Type = electric | classic

# Assume we havs 4 bikes "available" and 1 "booked" in every stattions
# except id 80,81,82,88,90 since their capacity are 0
[
%{status: "available", type: "electric", dock_id: 1},
%{status: "available", type: "electric", dock_id: 1},
%{status: "available", type: "classic", dock_id: 1},
%{status: "available", type: "classic", dock_id: 1},
%{status: "off-duty", type: "classic", dock_id: 1},
%{status: "booked", type: "classic", dock_id: 1},
%{status: "available", type: "electric", dock_id: 2},
%{status: "available", type: "classic", dock_id: 2},
%{status: "available", type: "classic", dock_id: 2},
%{status: "available", type: "classic", dock_id: 2},
%{status: "booked", type: "classic", dock_id: 2},
%{status: "available", type: "electric", dock_id: 3},
%{status: "available", type: "classic", dock_id: 3},
%{status: "available", type: "classic", dock_id: 3},
%{status: "available", type: "classic", dock_id: 3},
%{status: "booked", type: "classic", dock_id: 3},
%{status: "available", type: "electric", dock_id: 4},
%{status: "available", type: "classic", dock_id: 4},
%{status: "available", type: "classic", dock_id: 4},
%{status: "available", type: "classic", dock_id: 4},
%{status: "booked", type: "classic", dock_id: 4},
%{status: "available", type: "electric", dock_id: 5},
%{status: "available", type: "classic", dock_id: 5},
%{status: "available", type: "classic", dock_id: 5},
%{status: "available", type: "classic", dock_id: 5},
%{status: "booked", type: "classic", dock_id: 5},
%{status: "available", type: "electric", dock_id: 6},
%{status: "available", type: "classic", dock_id: 6},
%{status: "available", type: "classic", dock_id: 6},
%{status: "available", type: "classic", dock_id: 6},
%{status: "booked", type: "classic", dock_id: 6},
%{status: "available", type: "electric", dock_id: 7},
%{status: "available", type: "classic", dock_id: 7},
%{status: "available", type: "classic", dock_id: 7},
%{status: "available", type: "classic", dock_id: 7},
%{status: "booked", type: "classic", dock_id: 7},
%{status: "available", type: "electric", dock_id: 8},
%{status: "available", type: "classic", dock_id: 8},
%{status: "available", type: "classic", dock_id: 8},
%{status: "available", type: "classic", dock_id: 8},
%{status: "booked", type: "classic", dock_id: 8},
%{status: "available", type: "electric", dock_id: 9},
%{status: "available", type: "classic", dock_id: 9},
%{status: "available", type: "classic", dock_id: 9},
%{status: "available", type: "classic", dock_id: 9},
%{status: "booked", type: "classic", dock_id: 9},
%{status: "available", type: "electric", dock_id: 10},
%{status: "available", type: "classic", dock_id: 10},
%{status: "available", type: "classic", dock_id: 10},
%{status: "available", type: "classic", dock_id: 10},
%{status: "booked", type: "classic", dock_id: 10},
%{status: "available", type: "electric", dock_id: 11},
%{status: "available", type: "classic", dock_id: 11},
%{status: "available", type: "classic", dock_id: 11},
%{status: "available", type: "classic", dock_id: 11},
%{status: "booked", type: "classic", dock_id: 11},
%{status: "available", type: "electric", dock_id: 12},
%{status: "available", type: "classic", dock_id: 12},
%{status: "available", type: "classic", dock_id: 12},
%{status: "available", type: "classic", dock_id: 12},
%{status: "booked", type: "classic", dock_id: 12},
%{status: "available", type: "electric", dock_id: 13},
%{status: "available", type: "classic", dock_id: 13},
%{status: "available", type: "classic", dock_id: 13},
%{status: "available", type: "classic", dock_id: 13},
%{status: "booked", type: "classic", dock_id: 13},
%{status: "available", type: "electric", dock_id: 14},
%{status: "available", type: "classic", dock_id: 14},
%{status: "available", type: "classic", dock_id: 14},
%{status: "available", type: "classic", dock_id: 14},
%{status: "booked", type: "classic", dock_id: 14},
%{status: "available", type: "electric", dock_id: 15},
%{status: "available", type: "classic", dock_id: 15},
%{status: "available", type: "classic", dock_id: 15},
%{status: "available", type: "classic", dock_id: 15},
%{status: "booked", type: "classic", dock_id: 15},
%{status: "available", type: "electric", dock_id: 16},
%{status: "available", type: "classic", dock_id: 16},
%{status: "available", type: "classic", dock_id: 16},
%{status: "available", type: "classic", dock_id: 16},
%{status: "booked", type: "classic", dock_id: 16},
%{status: "available", type: "electric", dock_id: 17},
%{status: "available", type: "classic", dock_id: 17},
%{status: "available", type: "classic", dock_id: 17},
%{status: "available", type: "classic", dock_id: 17},
%{status: "booked", type: "classic", dock_id: 17},
%{status: "available", type: "electric", dock_id: 18},
%{status: "available", type: "classic", dock_id: 18},
%{status: "available", type: "classic", dock_id: 18},
%{status: "available", type: "classic", dock_id: 18},
%{status: "booked", type: "classic", dock_id: 18},
%{status: "available", type: "electric", dock_id: 19},
%{status: "available", type: "classic", dock_id: 19},
%{status: "available", type: "classic", dock_id: 19},
%{status: "available", type: "classic", dock_id: 19},
%{status: "booked", type: "classic", dock_id: 19},
%{status: "available", type: "electric", dock_id: 20},
%{status: "available", type: "classic", dock_id: 20},
%{status: "available", type: "classic", dock_id: 20},
%{status: "available", type: "classic", dock_id: 20},
%{status: "booked", type: "classic", dock_id: 20},
%{status: "available", type: "electric", dock_id: 21},
%{status: "available", type: "classic", dock_id: 21},
%{status: "available", type: "classic", dock_id: 21},
%{status: "available", type: "classic", dock_id: 21},
%{status: "booked", type: "classic", dock_id: 21},
%{status: "available", type: "electric", dock_id: 22},
%{status: "available", type: "classic", dock_id: 22},
%{status: "available", type: "classic", dock_id: 22},
%{status: "available", type: "classic", dock_id: 22},
%{status: "booked", type: "classic", dock_id: 22},
%{status: "available", type: "electric", dock_id: 23},
%{status: "available", type: "classic", dock_id: 23},
%{status: "available", type: "classic", dock_id: 23},
%{status: "available", type: "classic", dock_id: 23},
%{status: "booked", type: "classic", dock_id: 23},
%{status: "available", type: "electric", dock_id: 24},
%{status: "available", type: "classic", dock_id: 24},
%{status: "available", type: "classic", dock_id: 24},
%{status: "available", type: "classic", dock_id: 24},
%{status: "booked", type: "classic", dock_id: 24},
%{status: "available", type: "electric", dock_id: 25},
%{status: "available", type: "classic", dock_id: 25},
%{status: "available", type: "classic", dock_id: 25},
%{status: "available", type: "classic", dock_id: 25},
%{status: "booked", type: "classic", dock_id: 25},
%{status: "available", type: "electric", dock_id: 26},
%{status: "available", type: "classic", dock_id: 26},
%{status: "available", type: "classic", dock_id: 26},
%{status: "available", type: "classic", dock_id: 26},
%{status: "booked", type: "classic", dock_id: 26},
%{status: "available", type: "electric", dock_id: 27},
%{status: "available", type: "classic", dock_id: 27},
%{status: "available", type: "classic", dock_id: 27},
%{status: "available", type: "classic", dock_id: 27},
%{status: "booked", type: "classic", dock_id: 27},
%{status: "available", type: "electric", dock_id: 28},
%{status: "available", type: "classic", dock_id: 28},
%{status: "available", type: "classic", dock_id: 28},
%{status: "available", type: "classic", dock_id: 28},
%{status: "booked", type: "classic", dock_id: 28},
%{status: "available", type: "electric", dock_id: 29},
%{status: "available", type: "classic", dock_id: 29},
%{status: "available", type: "classic", dock_id: 29},
%{status: "available", type: "classic", dock_id: 29},
%{status: "booked", type: "classic", dock_id: 29},
%{status: "available", type: "electric", dock_id: 30},
%{status: "available", type: "classic", dock_id: 30},
%{status: "available", type: "classic", dock_id: 30},
%{status: "available", type: "classic", dock_id: 30},
%{status: "booked", type: "classic", dock_id: 30},
%{status: "available", type: "electric", dock_id: 31},
%{status: "available", type: "classic", dock_id: 31},
%{status: "available", type: "classic", dock_id: 31},
%{status: "available", type: "classic", dock_id: 31},
%{status: "booked", type: "classic", dock_id: 31},
%{status: "available", type: "electric", dock_id: 32},
%{status: "available", type: "classic", dock_id: 32},
%{status: "available", type: "classic", dock_id: 32},
%{status: "available", type: "classic", dock_id: 32},
%{status: "booked", type: "classic", dock_id: 32},
%{status: "available", type: "electric", dock_id: 33},
%{status: "available", type: "classic", dock_id: 33},
%{status: "available", type: "classic", dock_id: 33},
%{status: "available", type: "classic", dock_id: 33},
%{status: "booked", type: "classic", dock_id: 33},
%{status: "available", type: "electric", dock_id: 34},
%{status: "available", type: "classic", dock_id: 34},
%{status: "available", type: "classic", dock_id: 34},
%{status: "available", type: "classic", dock_id: 34},
%{status: "booked", type: "classic", dock_id: 34},
%{status: "available", type: "electric", dock_id: 35},
%{status: "available", type: "classic", dock_id: 35},
%{status: "available", type: "classic", dock_id: 35},
%{status: "available", type: "classic", dock_id: 35},
%{status: "booked", type: "classic", dock_id: 35},
%{status: "available", type: "electric", dock_id: 36},
%{status: "available", type: "classic", dock_id: 36},
%{status: "available", type: "classic", dock_id: 36},
%{status: "available", type: "classic", dock_id: 36},
%{status: "booked", type: "classic", dock_id: 36},
%{status: "available", type: "electric", dock_id: 37},
%{status: "available", type: "classic", dock_id: 37},
%{status: "available", type: "classic", dock_id: 37},
%{status: "available", type: "classic", dock_id: 37},
%{status: "booked", type: "classic", dock_id: 37},
%{status: "available", type: "electric", dock_id: 38},
%{status: "available", type: "classic", dock_id: 38},
%{status: "available", type: "classic", dock_id: 38},
%{status: "available", type: "classic", dock_id: 38},
%{status: "booked", type: "classic", dock_id: 38},
%{status: "available", type: "electric", dock_id: 39},
%{status: "available", type: "classic", dock_id: 39},
%{status: "available", type: "classic", dock_id: 39},
%{status: "available", type: "classic", dock_id: 39},
%{status: "booked", type: "classic", dock_id: 39},
%{status: "available", type: "electric", dock_id: 40},
%{status: "available", type: "classic", dock_id: 40},
%{status: "available", type: "classic", dock_id: 40},
%{status: "available", type: "classic", dock_id: 40},
%{status: "booked", type: "classic", dock_id: 40},
%{status: "available", type: "electric", dock_id: 41},
%{status: "available", type: "classic", dock_id: 41},
%{status: "available", type: "classic", dock_id: 41},
%{status: "available", type: "classic", dock_id: 41},
%{status: "booked", type: "classic", dock_id: 41},
%{status: "available", type: "electric", dock_id: 42},
%{status: "available", type: "classic", dock_id: 42},
%{status: "available", type: "classic", dock_id: 42},
%{status: "available", type: "classic", dock_id: 42},
%{status: "booked", type: "classic", dock_id: 42},
%{status: "available", type: "electric", dock_id: 43},
%{status: "available", type: "classic", dock_id: 43},
%{status: "available", type: "classic", dock_id: 43},
%{status: "available", type: "classic", dock_id: 43},
%{status: "booked", type: "classic", dock_id: 43},
%{status: "available", type: "electric", dock_id: 44},
%{status: "available", type: "classic", dock_id: 44},
%{status: "available", type: "classic", dock_id: 44},
%{status: "available", type: "classic", dock_id: 44},
%{status: "booked", type: "classic", dock_id: 44},
%{status: "available", type: "electric", dock_id: 45},
%{status: "available", type: "classic", dock_id: 45},
%{status: "available", type: "classic", dock_id: 45},
%{status: "available", type: "classic", dock_id: 45},
%{status: "booked", type: "classic", dock_id: 45},
%{status: "available", type: "electric", dock_id: 46},
%{status: "available", type: "classic", dock_id: 46},
%{status: "available", type: "classic", dock_id: 46},
%{status: "available", type: "classic", dock_id: 46},
%{status: "booked", type: "classic", dock_id: 46},
%{status: "available", type: "electric", dock_id: 47},
%{status: "available", type: "classic", dock_id: 47},
%{status: "available", type: "classic", dock_id: 47},
%{status: "available", type: "classic", dock_id: 47},
%{status: "booked", type: "classic", dock_id: 47},
%{status: "available", type: "electric", dock_id: 48},
%{status: "available", type: "classic", dock_id: 48},
%{status: "available", type: "classic", dock_id: 48},
%{status: "available", type: "classic", dock_id: 48},
%{status: "booked", type: "classic", dock_id: 48},
%{status: "available", type: "electric", dock_id: 49},
%{status: "available", type: "classic", dock_id: 49},
%{status: "available", type: "classic", dock_id: 49},
%{status: "available", type: "classic", dock_id: 49},
%{status: "booked", type: "classic", dock_id: 49},
%{status: "available", type: "electric", dock_id: 50},
%{status: "available", type: "classic", dock_id: 50},
%{status: "available", type: "classic", dock_id: 50},
%{status: "available", type: "classic", dock_id: 50},
%{status: "booked", type: "classic", dock_id: 50},
%{status: "available", type: "electric", dock_id: 51},
%{status: "available", type: "classic", dock_id: 51},
%{status: "available", type: "classic", dock_id: 51},
%{status: "available", type: "classic", dock_id: 51},
%{status: "booked", type: "classic", dock_id: 51},
%{status: "available", type: "electric", dock_id: 52},
%{status: "available", type: "classic", dock_id: 52},
%{status: "available", type: "classic", dock_id: 52},
%{status: "available", type: "classic", dock_id: 52},
%{status: "booked", type: "classic", dock_id: 52},
%{status: "available", type: "electric", dock_id: 53},
%{status: "available", type: "classic", dock_id: 53},
%{status: "available", type: "classic", dock_id: 53},
%{status: "available", type: "classic", dock_id: 53},
%{status: "booked", type: "classic", dock_id: 53},
%{status: "available", type: "electric", dock_id: 54},
%{status: "available", type: "classic", dock_id: 54},
%{status: "available", type: "classic", dock_id: 54},
%{status: "available", type: "classic", dock_id: 54},
%{status: "booked", type: "classic", dock_id: 54},
%{status: "available", type: "electric", dock_id: 55},
%{status: "available", type: "classic", dock_id: 55},
%{status: "available", type: "classic", dock_id: 55},
%{status: "available", type: "classic", dock_id: 55},
%{status: "booked", type: "classic", dock_id: 55},
%{status: "available", type: "electric", dock_id: 56},
%{status: "available", type: "classic", dock_id: 56},
%{status: "available", type: "classic", dock_id: 56},
%{status: "available", type: "classic", dock_id: 56},
%{status: "booked", type: "classic", dock_id: 56},
%{status: "available", type: "electric", dock_id: 57},
%{status: "available", type: "classic", dock_id: 57},
%{status: "available", type: "classic", dock_id: 57},
%{status: "available", type: "classic", dock_id: 57},
%{status: "booked", type: "classic", dock_id: 57},
%{status: "available", type: "electric", dock_id: 58},
%{status: "available", type: "classic", dock_id: 58},
%{status: "available", type: "classic", dock_id: 58},
%{status: "available", type: "classic", dock_id: 58},
%{status: "booked", type: "classic", dock_id: 58},
%{status: "available", type: "electric", dock_id: 59},
%{status: "available", type: "classic", dock_id: 59},
%{status: "available", type: "classic", dock_id: 59},
%{status: "available", type: "classic", dock_id: 59},
%{status: "booked", type: "classic", dock_id: 59},
%{status: "available", type: "electric", dock_id: 60},
%{status: "available", type: "classic", dock_id: 60},
%{status: "available", type: "classic", dock_id: 60},
%{status: "available", type: "classic", dock_id: 60},
%{status: "booked", type: "classic", dock_id: 60},
%{status: "available", type: "electric", dock_id: 61},
%{status: "available", type: "classic", dock_id: 61},
%{status: "available", type: "classic", dock_id: 61},
%{status: "available", type: "classic", dock_id: 61},
%{status: "booked", type: "classic", dock_id: 61},
%{status: "available", type: "electric", dock_id: 62},
%{status: "available", type: "classic", dock_id: 62},
%{status: "available", type: "classic", dock_id: 62},
%{status: "available", type: "classic", dock_id: 62},
%{status: "booked", type: "classic", dock_id: 62},
%{status: "available", type: "electric", dock_id: 63},
%{status: "available", type: "classic", dock_id: 63},
%{status: "available", type: "classic", dock_id: 63},
%{status: "available", type: "classic", dock_id: 63},
%{status: "booked", type: "classic", dock_id: 63},
%{status: "available", type: "electric", dock_id: 64},
%{status: "available", type: "classic", dock_id: 64},
%{status: "available", type: "classic", dock_id: 64},
%{status: "available", type: "classic", dock_id: 64},
%{status: "booked", type: "classic", dock_id: 64},
%{status: "available", type: "electric", dock_id: 65},
%{status: "available", type: "classic", dock_id: 65},
%{status: "available", type: "classic", dock_id: 65},
%{status: "available", type: "classic", dock_id: 65},
%{status: "booked", type: "classic", dock_id: 65},
%{status: "available", type: "electric", dock_id: 66},
%{status: "available", type: "classic", dock_id: 66},
%{status: "available", type: "classic", dock_id: 66},
%{status: "available", type: "classic", dock_id: 66},
%{status: "booked", type: "classic", dock_id: 66},
%{status: "available", type: "electric", dock_id: 67},
%{status: "available", type: "classic", dock_id: 67},
%{status: "available", type: "classic", dock_id: 67},
%{status: "available", type: "classic", dock_id: 67},
%{status: "booked", type: "classic", dock_id: 67},
%{status: "available", type: "electric", dock_id: 68},
%{status: "available", type: "classic", dock_id: 68},
%{status: "available", type: "classic", dock_id: 68},
%{status: "available", type: "classic", dock_id: 68},
%{status: "booked", type: "classic", dock_id: 68},
%{status: "available", type: "electric", dock_id: 69},
%{status: "available", type: "classic", dock_id: 69},
%{status: "available", type: "classic", dock_id: 69},
%{status: "available", type: "classic", dock_id: 69},
%{status: "booked", type: "classic", dock_id: 69},
%{status: "available", type: "electric", dock_id: 70},
%{status: "available", type: "classic", dock_id: 70},
%{status: "available", type: "classic", dock_id: 70},
%{status: "available", type: "classic", dock_id: 70},
%{status: "booked", type: "classic", dock_id: 70},
%{status: "available", type: "electric", dock_id: 71},
%{status: "available", type: "classic", dock_id: 71},
%{status: "available", type: "classic", dock_id: 71},
%{status: "available", type: "classic", dock_id: 71},
%{status: "booked", type: "classic", dock_id: 71},
%{status: "available", type: "electric", dock_id: 72},
%{status: "available", type: "classic", dock_id: 72},
%{status: "available", type: "classic", dock_id: 72},
%{status: "available", type: "classic", dock_id: 72},
%{status: "booked", type: "classic", dock_id: 72},
%{status: "available", type: "electric", dock_id: 73},
%{status: "available", type: "classic", dock_id: 73},
%{status: "available", type: "classic", dock_id: 73},
%{status: "available", type: "classic", dock_id: 73},
%{status: "booked", type: "classic", dock_id: 73},
%{status: "available", type: "electric", dock_id: 74},
%{status: "available", type: "classic", dock_id: 74},
%{status: "available", type: "classic", dock_id: 74},
%{status: "available", type: "classic", dock_id: 74},
%{status: "booked", type: "classic", dock_id: 74},
%{status: "available", type: "electric", dock_id: 75},
%{status: "available", type: "classic", dock_id: 75},
%{status: "available", type: "classic", dock_id: 75},
%{status: "available", type: "classic", dock_id: 75},
%{status: "booked", type: "classic", dock_id: 75},
%{status: "available", type: "electric", dock_id: 76},
%{status: "available", type: "classic", dock_id: 76},
%{status: "available", type: "classic", dock_id: 76},
%{status: "available", type: "classic", dock_id: 76},
%{status: "booked", type: "classic", dock_id: 76},
%{status: "available", type: "electric", dock_id: 77},
%{status: "available", type: "classic", dock_id: 77},
%{status: "available", type: "classic", dock_id: 77},
%{status: "available", type: "classic", dock_id: 77},
%{status: "booked", type: "classic", dock_id: 77},
%{status: "available", type: "electric", dock_id: 78},
%{status: "available", type: "classic", dock_id: 78},
%{status: "available", type: "classic", dock_id: 78},
%{status: "available", type: "classic", dock_id: 78},
%{status: "booked", type: "classic", dock_id: 78},
%{status: "available", type: "electric", dock_id: 79},
%{status: "available", type: "classic", dock_id: 79},
%{status: "available", type: "classic", dock_id: 79},
%{status: "available", type: "classic", dock_id: 79},
%{status: "booked", type: "classic", dock_id: 79},

%{status: "available", type: "electric", dock_id: 83},
%{status: "available", type: "classic", dock_id: 83},
%{status: "available", type: "classic", dock_id: 83},
%{status: "available", type: "classic", dock_id: 83},
%{status: "booked", type: "classic", dock_id: 83},
%{status: "available", type: "electric", dock_id: 84},
%{status: "available", type: "classic", dock_id: 84},
%{status: "available", type: "classic", dock_id: 84},
%{status: "available", type: "classic", dock_id: 84},
%{status: "booked", type: "classic", dock_id: 84},
%{status: "available", type: "electric", dock_id: 85},
%{status: "available", type: "classic", dock_id: 85},
%{status: "available", type: "classic", dock_id: 85},
%{status: "available", type: "classic", dock_id: 85},
%{status: "booked", type: "classic", dock_id: 85},
%{status: "available", type: "electric", dock_id: 86},
%{status: "available", type: "classic", dock_id: 86},
%{status: "available", type: "classic", dock_id: 86},
%{status: "available", type: "classic", dock_id: 86},
%{status: "booked", type: "classic", dock_id: 86},
%{status: "available", type: "electric", dock_id: 87},
%{status: "available", type: "classic", dock_id: 87},
%{status: "available", type: "classic", dock_id: 87},
%{status: "available", type: "classic", dock_id: 87},
%{status: "booked", type: "classic", dock_id: 87},

%{status: "available", type: "electric", dock_id: 89},
%{status: "available", type: "classic", dock_id: 89},
%{status: "available", type: "classic", dock_id: 89},
%{status: "available", type: "classic", dock_id: 89},
%{status: "booked", type: "classic", dock_id: 89},

%{status: "in-use", type: "electric"},
%{status: "in-use", type: "electric"},
%{status: "in-use", type: "classic"},
%{status: "in-use", type: "classic"},
%{status: "in-use", type: "classic"},
%{status: "in-use", type: "classic"},
%{status: "in-use", type: "classic"},
]
|> Enum.map(fn data -> Bike.changeset(%Bike{}, data) end)
|> Enum.each(fn changeset -> Repo.insert!(changeset) end)


[
  %{name: "AHHAA", img: "ahhaa.jpg", start_dock_id: 46, end_dock_id: 2},
  %{name: "Tartu Kunstimuuseum", img: "museum.jpg", start_dock_id: 47, end_dock_id: 24},
  %{name: "Botanical Garden of the University of Tartu", img: "garden.jpg", start_dock_id: 16, end_dock_id: 4},
  %{name: "Tagurpidi Maja", img: "tagurpidi.jpg", start_dock_id: 13, end_dock_id: 5},
]
|> Enum.map(fn data -> Route.changeset(%Route{}, data) end)
|> Enum.each(fn changeset -> Repo.insert!(changeset) end)
